name: backend
dependencies:
  - Python==3.8.5
  - psycopg2
  - pip
  - pip:
    - Django==3.1.2
    - djangorestframework==3.12.1
    - djangorestframework-simplejwt==4.4.0
    - django-any-imagefield==1.1
    - Pillow==7.2.0
    - flake8
    - gunicorn
    - django-cors-headers
