# Generated by Django 3.1.2 on 2020-10-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
    ]
