# Generated by Django 3.1.2 on 2020-10-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'friend_request_pending'), (2, 'friend_request_accepted'), (3, 'friend_request_rejected')], null=True)),
            ],
        ),
    ]
